import { useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { HeroImage } from '../components/HeroImage';
import { NavBar } from '../components/NavBar';
import { ContactForm } from '../components/ContactForm';
import { HeadingOne } from '../components/HeadingOne';

const Home: NextPage = () => {
  const [isContact, setIsContact] = useState(false);
  return (
    <div>
      <Head>
        <title>Midwestern Interactive</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <main>
        <NavBar setIsContact={setIsContact} isContact={false} />
        <HeroImage />
        <HeadingOne />
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
