import { useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { HeroImage } from '../components/HeroImage';
import { NavBar } from '../components/NavBar';
import { ContactForm } from '../components/ContactForm';
import { HeadingOne } from '../components/HeadingOne';
import styles from '../styles/index.module.scss';

const Home: NextPage = () => {
  const [isContact, setIsContact] = useState(false);
  return (
    <div className="stuff">
      <Head>
        <title>Midwestern Interactive</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <main>
        <div className={styles.mainWrapper}>
          <NavBar setIsContact={setIsContact} isContact={isContact} />
          {!isContact && <HeroImage />}
          {!isContact && (
            <HeadingOne>
              Remove the duplicates in 2 Javascript arrays (found in readme),
              add the results to an array and output the list of distinct names
              in an unordered list below this paragraph when <a>this link</a> is
              clicked. If the operation has been completed already, notify the
              user that this has already been done.
            </HeadingOne>
          )}
          {isContact && (
            <HeadingOne>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              dos eiusmod tempor incididunt ut labore et trace dolore magna
              aliqua.
              <br />
              <br />
              Proin sagittis nisl rhoncus mattis rhoncus. At augue eget arcu
              dictum varius duis at consectetur lorem.
            </HeadingOne>
          )}

          {isContact && <ContactForm />}
        </div>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
